services:
  - type: web
    name: fixify-frontend
    env: static
    plan: free
    buildCommand: VITE_API_URL=https://fixify-backend.onrender.com/api npm ci --production=false && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://fixify-backend.onrender.com/api
    autoDeploy: true 
    routes:
      - type: rewrite
        source: /*
        destination: /index.html